### ISSUE TITLE
Add explicit RSS link

### ISSUE THREAD

**Issue by Hanse00** [fediverse-devnet/feditest.org#1]
When browsing the FediTest website, and specifically the Blog page, I was unsure if RSS was supported. Thankfully it turns out that it is! Surfacing this clearly to visitors would be great. My suggestion would be adding a link somewhere on the blog page, which explicitly directs folks to the RSS feed.

I’m happy to implement this myself, but didn’t want to go any further before checking in to ensure that’s a desired change.

**Comment by jernst** [comment]
RSS is cool, so absolutely please do!
